"""Demo adapter - serves synthetic data generated by `lodestar demo-data`."""
from __future__ import annotations

from ....models import ControlHealth, Finding
from .base import Adapter, AdapterResult


class MockAdapter(Adapter):
    name = "mock"

    def fetch(self, ctx) -> AdapterResult:
        if not ctx.dataset:
            return AdapterResult(warnings=["mock adapter selected but no demo dataset loaded"])
        block = (ctx.dataset.get("domains") or {}).get(self.domain.value)
        if not block:
            return AdapterResult(warnings=[f"no demo data for {self.domain.value}"])
        findings = [Finding.model_validate(f) for f in block.get("findings", [])]
        health = ControlHealth.model_validate(block["health"]) if block.get("health") else None
        return AdapterResult(findings=findings, health=health)
